global:
  scrape_interval:     5s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
    static_configs:
      - targets:
        - 'cadvisor.server:8080'

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
    static_configs:
      - targets:
        - 'node-exporter.server:9100'